main = "src/index.ts"
compatibility_date = "2023-12-18"

#################### Environment names ####################
# dev should never actually get deployed anywhere
[env.dev]
name = "health-worker-dev"

# we don't have a hard-coded name for preview. we instead have to generate it at build time and append it to this file.

# staging is the same as a preview on main:
[env.staging]
name = "health-worker-staging"

# production gets the proper name
[env.production]
name = "health-worker-production"
